<?php
/**
 * ConditionGroup
 *
 * PHP version 5
 *
 * @category Class
 * @package  WebApiActiveQueryBuilder
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QueryBuilderApi
 *
 * Active Query Builder Web API lets create, analyze and modify SQL queries for different database servers using RESTful HTTP requests to a cloud-based service. It requires SQL execution context (information about database schema and used database server) to be stored under the registered account at https://webapi.activequerybuilder.com/.
 *
 * OpenAPI spec version: 1.1.6
 * Contact: support@activedbsoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace WebApiActiveQueryBuilder;

use \ArrayAccess;

/**
 * ConditionGroup Class Doc Comment
 *
 * @category    Class */
 // @description Group of conditions joined with the same boolean operator.
/** 
 * @package     WebApiActiveQueryBuilder
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConditionGroup implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ConditionGroup';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'junction_type' => 'string',
        'conditions' => '\WebApiActiveQueryBuilder\Condition[]',
        'condition_groups' => '\WebApiActiveQueryBuilder\ConditionGroup[]'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'junction_type' => 'junctionType',
        'conditions' => 'conditions',
        'condition_groups' => 'conditionGroups'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'junction_type' => 'setJunctionType',
        'conditions' => 'setConditions',
        'condition_groups' => 'setConditionGroups'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'junction_type' => 'getJunctionType',
        'conditions' => 'getConditions',
        'condition_groups' => 'getConditionGroups'
    );

    public static function getters()
    {
        return self::$getters;
    }

    const JUNCTION_TYPE_AND = 'And';
    const JUNCTION_TYPE_OR = 'Or';
    const JUNCTION_TYPE_ANY = 'Any';
    const JUNCTION_TYPE_ALL = 'All';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getJunctionTypeAllowableValues()
    {
        return [
            self::JUNCTION_TYPE_AND,
            self::JUNCTION_TYPE_OR,
            self::JUNCTION_TYPE_ANY,
            self::JUNCTION_TYPE_ALL,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['junction_type'] = isset($data['junction_type']) ? $data['junction_type'] : null;
        $this->container['conditions'] = isset($data['conditions']) ? $data['conditions'] : null;
        $this->container['condition_groups'] = isset($data['condition_groups']) ? $data['condition_groups'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        $allowed_values = array("And", "Or", "Any", "All");
        if (!in_array($this->container['junction_type'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'junction_type', must be one of #{allowed_values}.";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        $allowed_values = array("And", "Or", "Any", "All");
        if (!in_array($this->container['junction_type'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets junction_type
     * @return string
     */
    public function getJunctionType()
    {
        return $this->container['junction_type'];
    }

    /**
     * Sets junction_type
     * @param string $junction_type Type of junction. All = AND; Any = OR.
     * @return $this
     */
    public function setJunctionType($junction_type)
    {
        $allowed_values = array('And', 'Or', 'Any', 'All');
        if (!in_array($junction_type, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'junction_type', must be one of 'And', 'Or', 'Any', 'All'");
        }
        $this->container['junction_type'] = $junction_type;

        return $this;
    }

    /**
     * Gets conditions
     * @return \WebApiActiveQueryBuilder\Condition[]
     */
    public function getConditions()
    {
        return $this->container['conditions'];
    }

    /**
     * Sets conditions
     * @param \WebApiActiveQueryBuilder\Condition[] $conditions List of conditions to join.
     * @return $this
     */
    public function setConditions($conditions)
    {
        $this->container['conditions'] = $conditions;

        return $this;
    }

    /**
     * Gets condition_groups
     * @return \WebApiActiveQueryBuilder\ConditionGroup[]
     */
    public function getConditionGroups()
    {
        return $this->container['condition_groups'];
    }

    /**
     * Sets condition_groups
     * @param \WebApiActiveQueryBuilder\ConditionGroup[] $condition_groups List of nested condition groups to join them with a different boolean operator.
     * @return $this
     */
    public function setConditionGroups($condition_groups)
    {
        $this->container['condition_groups'] = $condition_groups;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\WebApiActiveQueryBuilder\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\WebApiActiveQueryBuilder\ObjectSerializer::sanitizeForSerialization($this));
    }
}


